name: Bug Report
description: Report a bug in the React Native MCP Server
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Call tool '...'
        2. With parameters '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: MCP Server Version
      description: Run `npm list -g @mrnitro360/react-native-mcp-guide`
      placeholder: "1.1.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version`
      placeholder: "v18.0.0"
    validations:
      required: true

  - type: dropdown
    id: client
    attributes:
      label: MCP Client
      description: Which MCP client are you using?
      options:
        - Claude Desktop
        - Claude CLI
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    id: tool
    attributes:
      label: Affected Tool
      description: Which tool is causing the issue?
      options:
        - analyze_component
        - analyze_codebase_comprehensive
        - analyze_codebase_performance
        - remediate_code
        - refactor_component
        - generate_component_test
        - analyze_testing_strategy
        - analyze_test_coverage
        - upgrade_packages
        - resolve_dependencies
        - audit_packages
        - migrate_packages
        - optimize_performance
        - architecture_advice
        - debug_issue
        - check_for_updates
        - get_version_info
        - Not specific to a tool
        - Unknown
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      placeholder: |
        // Your code here
      render: typescript

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, paste any error messages or logs
      placeholder: |
        Error messages or stack traces
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, related issues, etc.)
